# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
import cv2
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene, QMenu

# from UI.GraphicsView import GraphicsView

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1126, 898)


        self.graphicsView = QtWidgets.QGraphicsView(Form)
        # self.graphicsView = GraphicsView()
        self.graphicsView.setGeometry(QtCore.QRect(70, 30, 441, 811))
        self.graphicsView.setObjectName("graphicsView")


        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(780, 140, 191, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(780, 200, 341, 351))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 20, 60, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 40, 60, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 60, 60, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 80, 60, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 100, 60, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 140, 60, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 120, 60, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(510, 90, 60, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(510, 50, 60, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(510, 10, 60, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(510, 70, 60, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(510, 130, 60, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(510, 30, 60, 20))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(510, 110, 60, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 370, 60, 20))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(120, 350, 60, 20))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(120, 390, 60, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(120, 450, 60, 20))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(120, 410, 60, 20))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(120, 430, 60, 20))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(120, 470, 60, 20))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setGeometry(QtCore.QRect(120, 230, 60, 20))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setGeometry(QtCore.QRect(120, 210, 60, 20))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Form)
        self.pushButton_24.setGeometry(QtCore.QRect(120, 250, 60, 20))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(Form)
        self.pushButton_25.setGeometry(QtCore.QRect(120, 310, 60, 20))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(Form)
        self.pushButton_26.setGeometry(QtCore.QRect(120, 270, 60, 20))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(Form)
        self.pushButton_27.setGeometry(QtCore.QRect(120, 290, 60, 20))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(Form)
        self.pushButton_28.setGeometry(QtCore.QRect(120, 330, 60, 20))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setGeometry(QtCore.QRect(40, 440, 60, 20))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(Form)
        self.pushButton_30.setGeometry(QtCore.QRect(40, 470, 60, 20))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(Form)
        self.pushButton_31.setGeometry(QtCore.QRect(40, 500, 60, 20))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(Form)
        self.pushButton_32.setGeometry(QtCore.QRect(40, 410, 60, 20))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(Form)
        self.pushButton_33.setGeometry(QtCore.QRect(40, 380, 60, 20))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(Form)
        self.pushButton_34.setGeometry(QtCore.QRect(40, 200, 60, 20))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(Form)
        self.pushButton_35.setGeometry(QtCore.QRect(40, 230, 60, 20))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(Form)
        self.pushButton_36.setGeometry(QtCore.QRect(40, 260, 60, 20))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(Form)
        self.pushButton_37.setGeometry(QtCore.QRect(40, 350, 60, 20))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(Form)
        self.pushButton_38.setGeometry(QtCore.QRect(40, 290, 60, 20))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(Form)
        self.pushButton_39.setGeometry(QtCore.QRect(40, 530, 60, 20))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(Form)
        self.pushButton_40.setGeometry(QtCore.QRect(40, 170, 60, 20))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(Form)
        self.pushButton_41.setGeometry(QtCore.QRect(40, 560, 60, 20))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(Form)
        self.pushButton_42.setGeometry(QtCore.QRect(40, 320, 60, 20))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(Form)
        self.pushButton_43.setGeometry(QtCore.QRect(40, 590, 60, 20))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(Form)
        self.pushButton_44.setGeometry(QtCore.QRect(40, 710, 60, 20))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(Form)
        self.pushButton_45.setGeometry(QtCore.QRect(40, 650, 60, 20))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(Form)
        self.pushButton_46.setGeometry(QtCore.QRect(40, 620, 60, 20))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(Form)
        self.pushButton_47.setGeometry(QtCore.QRect(40, 680, 60, 20))
        self.pushButton_47.setObjectName("pushButton_47")
        self.graphicsView.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_2.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.pushButton_22.raise_()
        self.pushButton_24.raise_()
        self.pushButton_26.raise_()
        self.pushButton_28.raise_()
        self.pushButton_27.raise_()
        self.pushButton_23.raise_()
        self.pushButton_25.raise_()
        self.pushButton_29.raise_()
        self.pushButton_30.raise_()
        self.pushButton_31.raise_()
        self.pushButton_32.raise_()
        self.pushButton_33.raise_()
        self.pushButton_34.raise_()
        self.pushButton_35.raise_()
        self.pushButton_36.raise_()
        self.pushButton_37.raise_()
        self.pushButton_38.raise_()
        self.pushButton_39.raise_()
        self.pushButton_40.raise_()
        self.pushButton_41.raise_()
        self.pushButton_42.raise_()
        self.pushButton_43.raise_()
        self.pushButton_44.raise_()
        self.pushButton_45.raise_()
        self.pushButton_46.raise_()
        self.pushButton_47.raise_()





        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.show_back_image()


        # 默认显示标准图像

    def show_back_image(self):
        fileName = '/UI/tomarkB.png'
        # fileName = cv2.imdecode(np.fromfile(path, dtype=np.uint8), 1)
        self.graphicsView.scene_img = QGraphicsScene()
        self.imgShow = QPixmap()
        self.imgShow.load(fileName)
        self.imgShowItem = QGraphicsPixmapItem()
        self.imgShowItem.setPixmap(QPixmap(self.imgShow))
        # self.imgShowItem.setPixmap(QPixmap(self.imgShow).scaled(8000,  8000))    //自己设定尺寸
        self.graphicsView.scene_img.addItem(self.imgShowItem)
        self.graphicsView.setScene(self.graphicsView.scene_img)
        self.graphicsView.fitInView(QGraphicsPixmapItem(QPixmap(self.imgShow)))





    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "百会"))
        self.pushButton_2.setText(_translate("Form", "后顶"))
        self.pushButton_3.setText(_translate("Form", "强间"))
        self.pushButton_4.setText(_translate("Form", "脑户"))
        self.pushButton_5.setText(_translate("Form", "风府"))
        self.pushButton_6.setText(_translate("Form", "天柱"))
        self.pushButton_7.setText(_translate("Form", "哑门"))
        self.pushButton_8.setText(_translate("Form", "浮白"))
        self.pushButton_9.setText(_translate("Form", "脑空"))
        self.pushButton_10.setText(_translate("Form", "络却"))
        self.pushButton_11.setText(_translate("Form", "凤池"))
        self.pushButton_12.setText(_translate("Form", "完骨"))
        self.pushButton_13.setText(_translate("Form", "玉枕"))
        self.pushButton_14.setText(_translate("Form", "头窍阴"))
        self.pushButton_15.setText(_translate("Form", "脊中"))
        self.pushButton_16.setText(_translate("Form", "中枢"))
        self.pushButton_17.setText(_translate("Form", "悬枢"))
        self.pushButton_18.setText(_translate("Form", "腰俞"))
        self.pushButton_19.setText(_translate("Form", "命门"))
        self.pushButton_20.setText(_translate("Form", "腰阳关"))
        self.pushButton_21.setText(_translate("Form", "完骨"))
        self.pushButton_22.setText(_translate("Form", "陶道"))
        self.pushButton_23.setText(_translate("Form", "大椎"))
        self.pushButton_24.setText(_translate("Form", "身柱"))
        self.pushButton_25.setText(_translate("Form", "至阳"))
        self.pushButton_26.setText(_translate("Form", "神道"))
        self.pushButton_27.setText(_translate("Form", "灵台"))
        self.pushButton_28.setText(_translate("Form", "筋缩"))
        self.pushButton_29.setText(_translate("Form", "脾俞"))
        self.pushButton_30.setText(_translate("Form", "胃俞"))
        self.pushButton_31.setText(_translate("Form", "三焦俞"))
        self.pushButton_32.setText(_translate("Form", "胆俞"))
        self.pushButton_33.setText(_translate("Form", "肝俞"))
        self.pushButton_34.setText(_translate("Form", "风门"))
        self.pushButton_35.setText(_translate("Form", "肺俞"))
        self.pushButton_36.setText(_translate("Form", "厥阴俞"))
        self.pushButton_37.setText(_translate("Form", "膈俞"))
        self.pushButton_38.setText(_translate("Form", "心俞"))
        self.pushButton_39.setText(_translate("Form", "肾俞"))
        self.pushButton_40.setText(_translate("Form", "大抒"))
        self.pushButton_41.setText(_translate("Form", "气海俞"))
        self.pushButton_42.setText(_translate("Form", "督俞"))
        self.pushButton_43.setText(_translate("Form", "大肠俞"))
        self.pushButton_44.setText(_translate("Form", "大肠俞"))
        self.pushButton_45.setText(_translate("Form", "肾俞"))
        self.pushButton_46.setText(_translate("Form", "三焦俞"))
        self.pushButton_47.setText(_translate("Form", "气海俞"))



